version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ecomindalapp
      POSTGRES_USER: luis
      POSTGRES_PASSWORD: 1234

  web:
    build: .
    command: ./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=ecomindalapp
      - DATABASE_USER=luis
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data: